services:
  nginx:
    image: nginx:1.27.0-alpine3.19
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/srv
    ports:
      - "80:80"


  php-fpm:
    image: php:8.3-fpm-alpine3.20
    volumes:
      - ./:/srv


  localstack:
#    image: localstack/localstack:3.5
    image: localstack/localstack-pro:3.5
    container_name: localstack-main
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=s3,sqs,sns
      - DEBUG=1
      - START_WEB=1
      - VIRTUAL_HOST=localstack.loc
      - HOSTNAME=localstack
      - LOCALSTACK_HOST=localstack
    volumes:
      - './.localstack:/var/lib/localstack'
      - './init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh'
      - '/var/run/docker.sock:/var/run/docker.sock'